title: 玉米的博客
email: cornagreattaste@qq.com
description: 记录生活，赶走不开心。
url: "https://cornagrt.github.io"
author: CornAGrt
github_username: CornAGrt

# Build settings
theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed
